language: php

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libzmq3-dev

php:
  - 5.4
  - 5.5

before_script:
  - git clone https://github.com/mkoppanen/php-zmq.git
  - sh -c "cd php-zmq && phpize && ./configure && make --silent && sudo make install"
  - echo "extension=zmq.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - composer self-update
  - composer install --dev

script: phpunit --coverage-text